{% set name = "django-nose" %}
{% set version = "1.4.7" %}
{% set sha256 = "a4885cd002d65fd2de96e2bb2563ef477c3fbe207009360c015fca5c3b5561b7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - django >=1.8
    - nose >=1.2.1

test:
  imports:
    - django_nose
    - django_nose.management
    - django_nose.management.commands

about:
  home: http://github.com/django-nose/django-nose
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Makes your Django tests simple and snappy

  dev_url: http://github.com/django-nose/django-nose
  doc_url: https://django-nose.readthedocs.io/

extra:
  recipe-maintainers:
    - sodre
